# Generated by Django 6.0.3 on 2026-03-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabcierreturno',
            name='ch_codi_turno_caja',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cabcobranzacredito',
            name='ch_codi_turno_caja',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cabreciboegreso',
            name='ch_codi_turno_caja',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cabreciboingreso',
            name='ch_codi_turno_caja',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='movticket',
            name='ch_codi_turno_caja',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='movticket',
            name='ch_codi_turno_sld',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
