# Generated by Codex on 2026-04-29

from django.db import migrations, models


DAY_TOKENS = ['1', '01', '1.0', 'dia', 'Dia', 'DIA', 'day', 'Day', 'DAY']
NIGHT_TOKENS = ['2', '02', '2.0', 'noche', 'Noche', 'NOCHE', 'night', 'Night', 'NIGHT']


def normalize_turno_codes(apps, schema_editor):
    MovTicket = apps.get_model('movimientos', 'MovTicket')
    CabCobranzaCredito = apps.get_model('movimientos', 'CabCobranzaCredito')
    CabCierreTurno = apps.get_model('movimientos', 'CabCierreTurno')
    CabReciboEgreso = apps.get_model('movimientos', 'CabReciboEgreso')
    CabReciboIngreso = apps.get_model('movimientos', 'CabReciboIngreso')

    for model, field_name in (
        (MovTicket, 'ch_codi_turno_caja'),
        (MovTicket, 'ch_codi_turno_sld'),
        (CabCobranzaCredito, 'ch_codi_turno_caja'),
        (CabCierreTurno, 'ch_codi_turno_caja'),
        (CabReciboEgreso, 'ch_codi_turno_caja'),
        (CabReciboIngreso, 'ch_codi_turno_caja'),
    ):
        model.objects.filter(**{f'{field_name}__in': DAY_TOKENS}).update(**{field_name: '1'})
        model.objects.filter(**{f'{field_name}__in': NIGHT_TOKENS}).update(**{field_name: '2'})


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_alter_cabcierreturno_ch_codi_turno_caja_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_turno_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='movticket',
            name='ch_codi_turno_caja',
            field=models.CharField(blank=True, choices=[('1', 'Dia'), ('2', 'Noche')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='movticket',
            name='ch_codi_turno_sld',
            field=models.CharField(blank=True, choices=[('1', 'Dia'), ('2', 'Noche')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cabcobranzacredito',
            name='ch_codi_turno_caja',
            field=models.CharField(blank=True, choices=[('1', 'Dia'), ('2', 'Noche')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cabcierreturno',
            name='ch_codi_turno_caja',
            field=models.CharField(blank=True, choices=[('1', 'Dia'), ('2', 'Noche')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cabreciboegreso',
            name='ch_codi_turno_caja',
            field=models.CharField(blank=True, choices=[('1', 'Dia'), ('2', 'Noche')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cabreciboingreso',
            name='ch_codi_turno_caja',
            field=models.CharField(blank=True, choices=[('1', 'Dia'), ('2', 'Noche')], max_length=1, null=True),
        ),
        migrations.AddConstraint(
            model_name='movticket',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(ch_codi_turno_caja__in=['1', '2'])
                    | models.Q(ch_codi_turno_caja__isnull=True)
                    | models.Q(ch_codi_turno_caja='')
                ),
                name='mov_ticket_turno_caja_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='movticket',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(ch_codi_turno_sld__in=['1', '2'])
                    | models.Q(ch_codi_turno_sld__isnull=True)
                    | models.Q(ch_codi_turno_sld='')
                ),
                name='mov_ticket_turno_sld_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='cabcobranzacredito',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(ch_codi_turno_caja__in=['1', '2'])
                    | models.Q(ch_codi_turno_caja__isnull=True)
                    | models.Q(ch_codi_turno_caja='')
                ),
                name='cab_cobr_cred_turno_caja_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='cabcierreturno',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(ch_codi_turno_caja__in=['1', '2'])
                    | models.Q(ch_codi_turno_caja__isnull=True)
                    | models.Q(ch_codi_turno_caja='')
                ),
                name='cab_cierre_turno_caja_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='cabreciboegreso',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(ch_codi_turno_caja__in=['1', '2'])
                    | models.Q(ch_codi_turno_caja__isnull=True)
                    | models.Q(ch_codi_turno_caja='')
                ),
                name='cab_rec_egre_turno_caja_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='cabreciboingreso',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(ch_codi_turno_caja__in=['1', '2'])
                    | models.Q(ch_codi_turno_caja__isnull=True)
                    | models.Q(ch_codi_turno_caja='')
                ),
                name='cab_rec_ingr_turno_caja_valid',
            ),
        ),
    ]
