# Generated by Django 6.0.3 on 2026-03-16 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaeChofer',
            fields=[
                ('ch_codi_chofer', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('vc_desc_chofer', models.CharField(blank=True, max_length=100, null=True)),
                ('ch_nume_celu', models.CharField(blank=True, max_length=20, null=True)),
                ('ch_codi_usua_regi', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_codi_usua_modi', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_usua_regi', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_usua_modi', models.DateTimeField(blank=True, null=True)),
                ('vc_dire_chofer', models.CharField(blank=True, max_length=100, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_nume_dni', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Chofer',
                'db_table': 'MAE_CHOFER',
            },
        ),
        migrations.CreateModel(
            name='MaeCliente',
            fields=[
                ('ch_codi_cliente', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ch_ruc_cliente', models.CharField(blank=True, max_length=11, null=True)),
                ('vc_razo_soci_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('vc_dire_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('ch_codi_usua_regi', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_codi_usua_modi', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_usua_regi', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_usua_modi', models.DateTimeField(blank=True, null=True)),
                ('ch_esta_cliente_vip', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_esta_tarifa_unica', models.CharField(blank=True, max_length=1, null=True)),
                ('nu_impo_tarifa', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'db_table': 'MAE_CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='MaeGarita',
            fields=[
                ('ch_codi_garita', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('vc_desc_garita', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_codi_usua_regi', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_codi_usua_modi', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_usua_regi', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_usua_modi', models.DateTimeField(blank=True, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Garita',
                'db_table': 'MAE_GARITA',
            },
        ),
        migrations.CreateModel(
            name='MaePerfil',
            fields=[
                ('ch_codi_perfil', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('vc_desc_perfil', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_esta_perfil', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'db_table': 'MAE_PERFIL',
            },
        ),
        migrations.CreateModel(
            name='MaeProveedor',
            fields=[
                ('ch_codi_proveedor', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('vc_razo_soci_prov', models.CharField(blank=True, max_length=100, null=True)),
                ('ch_ruc_prov', models.CharField(blank=True, max_length=11, null=True)),
                ('vc_dire_prov', models.CharField(blank=True, max_length=100, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_codi_usua_regi', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_codi_usua_modi', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_usua_modi', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_usua_regi', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'db_table': 'MAE_PROVEEDOR',
            },
        ),
        migrations.CreateModel(
            name='MaeSistema',
            fields=[
                ('ch_codi_sistema', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('vc_desl_sistema', models.CharField(blank=True, max_length=50, null=True)),
                ('vc_desc_sistema', models.CharField(blank=True, max_length=30, null=True)),
                ('ch_esta_sistema', models.CharField(blank=True, max_length=1, null=True)),
                ('vc_desc_logo', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Sistema',
                'db_table': 'MAE_SISTEMA',
            },
        ),
        migrations.CreateModel(
            name='MaeTipoDocumento',
            fields=[
                ('ch_codi_tipo_dcmnt', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('vc_desc_tipo_dcmnt', models.CharField(blank=True, max_length=30, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_codi_usua_regi', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_codi_usua_modi', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_usua_regi', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_usua_modi', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'db_table': 'MAE_TIPO_DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='MaeTipoEgreso',
            fields=[
                ('ch_codi_tipo_egreso', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('vc_desc_tipo_egreso', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_codi_usua_regi', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_codi_usua_modi', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_usua_regi', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_usua_modi', models.DateTimeField(blank=True, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Egreso',
                'db_table': 'MAE_TIPO_EGRESO',
            },
        ),
        migrations.CreateModel(
            name='MaeTipoIncidente',
            fields=[
                ('ch_codi_tipo_incidente', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('vc_desc_tipo_incidente', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_codi_usua_regi', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_codi_usua_modi', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_usua_regi', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_usua_modi', models.DateTimeField(blank=True, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Incidente',
                'db_table': 'MAE_TIPO_INCIDENTE',
            },
        ),
        migrations.CreateModel(
            name='MaeTipoIngreso',
            fields=[
                ('ch_codi_tipo_ingreso', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('vc_desc_tipo_ingreso', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_codi_usua_regi', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_codi_usua_modi', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_usua_regi', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_usua_modi', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ingreso',
                'db_table': 'MAE_TIPO_INGRESO',
            },
        ),
        migrations.CreateModel(
            name='MaeTipoVehiculo',
            fields=[
                ('ch_tipo_vehiculo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('vc_desc_tipo_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_codi_usua_regi', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_codi_usua_modi', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_usua_regi', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_usua_modi', models.DateTimeField(blank=True, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'db_table': 'MAE_TIPO_VEHICULO',
            },
        ),
        migrations.CreateModel(
            name='MaeUsuario',
            fields=[
                ('ch_codi_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vc_desc_nomb_usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('ch_codi_centro', models.CharField(blank=True, max_length=4, null=True)),
                ('vc_desc_apell_paterno', models.CharField(blank=True, max_length=30, null=True)),
                ('vc_desc_apell_materno', models.CharField(blank=True, max_length=30, null=True)),
                ('vc_desc_email_usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('vc_host_conexion', models.CharField(blank=True, max_length=30, null=True)),
                ('ch_esta_conexion', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_pass_usua', models.CharField(blank=True, max_length=10, null=True)),
                ('ch_codi_usua', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_ulti_actu', models.DateTimeField(blank=True, null=True)),
                ('ch_codi_cta_upch', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_esta_programa_todos', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_esta_horas_extra', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_esta_autoriza', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_tipo_usuario', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_pass_usua2', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'db_table': 'MAE_USUARIO',
            },
        ),
        migrations.CreateModel(
            name='MaeVariable',
            fields=[
                ('ch_codi_variable', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('vc_desc_variable', models.CharField(blank=True, max_length=70, null=True)),
                ('nu_nume_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('dt_fech_ulti_actu', models.DateTimeField(blank=True, null=True)),
                ('ch_codi_usua', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_valo_variable', models.CharField(blank=True, max_length=10, null=True)),
                ('nu_nume_valo_desde', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nu_nume_valo_hasta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ch_nume_valo_desde', models.CharField(blank=True, max_length=10, null=True)),
                ('ch_nume_valo_hasta', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Variable',
                'db_table': 'MAE_VARIABLE',
            },
        ),
        migrations.CreateModel(
            name='MaeModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_codi_modulo', models.CharField(max_length=3)),
                ('vc_desc_modulo', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_esta_modulo', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_codi_sistema', models.ForeignKey(db_column='CH_CODI_SISTEMA', on_delete=django.db.models.deletion.PROTECT, to='maestros.maesistema')),
            ],
            options={
                'verbose_name': 'Módulo',
                'db_table': 'MAE_MODULO',
                'unique_together': {('ch_codi_sistema', 'ch_codi_modulo')},
            },
        ),
        migrations.CreateModel(
            name='MaeCorrelativo',
            fields=[
                ('ch_codi_correlativo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ch_seri_actual', models.CharField(blank=True, max_length=4, null=True)),
                ('ch_nume_actual', models.CharField(blank=True, max_length=10, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_codi_usua_regi', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_codi_usua_modi', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_usua_regi', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_usua_modi', models.DateTimeField(blank=True, null=True)),
                ('ch_codi_tipo_dcmnt', models.ForeignKey(blank=True, db_column='CH_CODI_TIPO_DCMNT', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correlativos', to='maestros.maetipodocumento')),
            ],
            options={
                'verbose_name': 'Correlativo',
                'db_table': 'MAE_CORRELATIVO',
            },
        ),
        migrations.CreateModel(
            name='MaeVehiculo',
            fields=[
                ('ch_codi_vehiculo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ch_plac_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('nu_nume_llanta', models.IntegerField(blank=True, null=True)),
                ('ch_codi_usua_regi', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_codi_usua_modi', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_usua_regi', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_usua_modi', models.DateTimeField(blank=True, null=True)),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_esta_parqueado', models.CharField(blank=True, max_length=1, null=True)),
                ('nu_impo_alquiler', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ch_codi_chofer', models.ForeignKey(blank=True, db_column='CH_CODI_CHOFER', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='maestros.maechofer')),
                ('ch_codi_cliente', models.ForeignKey(blank=True, db_column='CH_CODI_CLIENTE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='maestros.maecliente')),
                ('ch_tipo_vehiculo', models.ForeignKey(blank=True, db_column='CH_TIPO_VEHICULO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='maestros.maetipovehiculo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'db_table': 'MAE_VEHICULO',
            },
        ),
        migrations.CreateModel(
            name='MaeOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_codi_sistema', models.CharField(max_length=3)),
                ('ch_codi_opcion', models.CharField(max_length=2)),
                ('vc_desc_opcion', models.CharField(blank=True, max_length=50, null=True)),
                ('vc_desc_nom_ventana', models.CharField(blank=True, max_length=50, null=True)),
                ('vc_tipo_opcion', models.CharField(blank=True, max_length=3, null=True)),
                ('vc_desc_icono_opcion', models.CharField(blank=True, max_length=50, null=True)),
                ('vc_desc_responsable', models.CharField(blank=True, max_length=50, null=True)),
                ('dt_fech_creacion_opcion', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_mod_opcion', models.DateTimeField(blank=True, null=True)),
                ('ch_esta_parametro', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_esta_opcion', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_desc_nom_corto', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_ruta_programa', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_esta_opcion_internet', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_ind_original', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_codi_modulo_fk', models.ForeignKey(db_column='CH_CODI_MODULO_FK_ID', on_delete=django.db.models.deletion.PROTECT, related_name='opciones', to='maestros.maemodulo')),
            ],
            options={
                'verbose_name': 'Opción',
                'db_table': 'MAE_OPCION',
                'unique_together': {('ch_codi_sistema', 'ch_codi_modulo_fk', 'ch_codi_opcion')},
            },
        ),
        migrations.CreateModel(
            name='AdmPerfilOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_codi_sistema', models.CharField(max_length=3)),
                ('ch_codi_modulo', models.CharField(max_length=3)),
                ('ch_codi_opcion', models.CharField(max_length=2)),
                ('ch_codi_perfil', models.ForeignKey(db_column='CH_CODI_PERFIL', on_delete=django.db.models.deletion.PROTECT, related_name='opciones_perfil', to='maestros.maeperfil')),
            ],
            options={
                'verbose_name': 'Perfil – Opción',
                'db_table': 'ADM_PERFIL_OPCIONES',
                'unique_together': {('ch_codi_sistema', 'ch_codi_modulo', 'ch_codi_opcion', 'ch_codi_perfil')},
            },
        ),
        migrations.CreateModel(
            name='MaePerfilMaeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_nume_asigna', models.CharField(max_length=3)),
                ('dt_fech_asigna', models.DateTimeField(blank=True, null=True)),
                ('ch_codi_usua_asigna', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_revoca', models.DateTimeField(blank=True, null=True)),
                ('ch_codi_usua_revoca', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_esta_perfil_usua', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_codi_perfil', models.ForeignKey(db_column='CH_CODI_PERFIL', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='maestros.maeperfil')),
                ('ch_codi_usuario', models.ForeignKey(db_column='CH_CODI_USUARIO', on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='maestros.maeusuario')),
            ],
            options={
                'verbose_name': 'Perfil – Usuario',
                'db_table': 'MAE_PERFIL_MAE_USUARIO',
                'unique_together': {('ch_codi_usuario', 'ch_codi_perfil', 'ch_nume_asigna')},
            },
        ),
        migrations.CreateModel(
            name='MaeGaritaXUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_esta_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('ch_codi_usua_regi', models.CharField(blank=True, max_length=15, null=True)),
                ('ch_codi_usua_modi', models.CharField(blank=True, max_length=15, null=True)),
                ('dt_fech_usua_regi', models.DateTimeField(blank=True, null=True)),
                ('dt_fech_usua_modi', models.DateTimeField(blank=True, null=True)),
                ('ch_codi_garita', models.ForeignKey(db_column='ch_codi_garita', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_garita', to='maestros.maegarita')),
                ('ch_codi_usuario', models.ForeignKey(db_column='ch_codi_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='garitas', to='maestros.maeusuario')),
            ],
            options={
                'verbose_name': 'Garita × Usuario',
                'db_table': 'mae_garita_x_usuario',
                'unique_together': {('ch_codi_garita', 'ch_codi_usuario')},
            },
        ),
    ]
